=head1 NAME

adwm-style -- advanced dynamic window manager for X: styles

=head1 SYNOPSIS

F<$HOME/.adwm/stylerc>

=head1 DESCRIPTION

B<adwm> is a light-weight, reparenting, dynamic tiling/stacking window
manager, intended on being fully controllable using only the keyboard:
the objective of all dynamic tiling window managers.  However, B<adwm>
also supports regular stacking floating window management as well, and
decorative frames are applied to windows in a number of circumstances.
To control the styling of the decorative border, B<adwm> supports
customizable style elements.

Decorative window borders can contain title text as well as buttons
(defined as pixmaps) that can perform a number of predefined actions ont
he window around which they appear.  Customizable style elements exist
to determine which pixmaps are displayed and under which conditions.

B<adwm> directly supports a WindowMaker style "dock".  Window Maker dock
applications are reparented into tiles within the dock.  These types
also support customizable style elements.

Customizable style elements are defined in an X Resource formatted
configuration file.  Styles can either be part of the main configuration
file, or they can be included or referenced from the main configuration
file.  It is typical to place the style elements in a file named
F<stylerc> in the same directory as the main configuration file (e.g. in
the F<$HOME/.adwm/stylerc> file).  See L</FILES>, below.

=head1 SYNTAX

The general syntax of style elements, as specified directly in the
B<adwm> resource file, is as follows:

=over

=over

=item Adwm*B<element>: I<E<lt>valueE<gt>>

=back

=back

Where the fields are defined as follows:

=over

=item B<element>

One of the elements described under L</ELEMENTS>.

=item I<E<lt>valueE<gt>> = {I<E<lt>pixmapE<gt>>|I<E<lt>fontE<gt>>|I<E<lt>colorE<gt>>|I<E<lt>numberE<gt>>|I<E<lt>stringE<gt>>}

The value depends on the element that is being specified.  Typically the
value is a path and name of a pixmap file, an X11 true-type or bitmapped
font specification, an X11 color specification, a number, a string, or a
specially formatted value, as follows:

=over 10

=item I<E<lt>pixmapE<gt>>

Pixmaps are specified with a full or relative path and file name.  When
the path is relative, it is relative to the directory in which the style
file resides.  Example:

=over

Adwm*B<button.iconify.pixmap>: I<pixmaps/min_focused.xpm>

=back

=item I<E<lt>fontE<gt>>

Fonts are specified with an XFT formatted font specification string.
Example:

=over

Adwm*B<normal.font>: I<Liberation Snas:size=9:medium>

=back

=item I<E<lt>colorE<gt>>

Colors are specified as X resource colors.  This can be a color name or
color specification.  Example:

=over

Adwm*B<selected.shadow>: I<#394870>

=back

=item I<E<lt>numberE<gt>>

A decimal number.  Example:

=over

=over

=item Adwm*B<title>: I<15>

=item Adwm*B<grips>: I<3>

=item

=back

=back

=item I<E<lt>stringE<gt>>

A specially formatted string as specified by the element definition.
Example:

=over

Adwm*B<titlelayout>: I<EFASLN  RIMC>

=back

=back

=back

=head1 ELEMENTS

The style elements are defined below.  Each heading provides the format
of the command resource (without the C<Adwm*> portion) and the possible
arguments for each element, in accordance with the element syntax
described above under L</SYNTAX>.

=over

=item B<font> I<E<lt>fontE<gt>>

Specifies the font to be used for title bar text.  Example:

=over

Adwm*B<font>: I<Liberation Sans:size=8:medium>

=back

=item B<border> I<E<lt>numberE<gt>>

Specifies the number of pixels of border that surrounds the title bar
and resize grips.  Typically set to one (1).  Example:

=over

Adwm*B<border>: I<1>

=back

=item B<margin> I<E<lt>numberE<gt>>

Specifies the margin between the title bar elements and the title bar
border.  Typically set to zero (0) to conserve screen real estate.
Example:

=over

Adwm*B<margin>: I<0>

=back

=item B<outline> I<E<lt>numberE<gt>>

Specifies the number of pixels to use to outline the title bar and
resize grips.  Example:

=over

Adwm*B<outline>: I<1>

=back

=item B<spacing> I<E<lt>numberE<gt>>

Specifies the number of pixels to be used between title bar elements.
Example:

=over

Adwm*B<spacing>: I<1>

=back

=item B<title> I<E<lt>numberE<gt>>

Specifies the height of the title bar in pixels.  Example:

=over

Adwm*B<title>: I<15>

=back

=item B<grips> I<E<lt>numberE<gt>>

Specifies the height of the resize grips in pixels.  Example:

=over

Adwm*B<grips>: I<3>

=back

=item B<E<lt>windowstateE<gt>>.B<E<lt>elementE<gt>> I<E<lt>valueE<gt>>

Specifies the style elements for the title bar, title, buttons and
resize grips in one of two possible states: (normal and selected).

B<E<lt>windowstateE<gt>> may be one of:

=over

=item B<font> I<E<lt>fontE<gt>>

font for the title;

=item B<drop> I<E<lt>numberE<gt>>

drop in pixels of the shadow;

=item B<shadow> I<E<lt>colorE<gt>>

color of the shadow;

=item B<border> I<E<lt>colorE<gt>>

color of the border;

=item B<button> I<E<lt>colorE<gt>>

background color of buttons;

=item B<bg> I<E<lt>colorE<gt>>

background color of title bar and grips; and,

=item B<fg> I<E<lt>colorE<gt>>

foreground color of the title.

=back

Example:

=over

=over

=item Adwm*B<selected.font>:   I<Liberation Sans:size=9:medium>

=item Adwm*B<selected.drop>:   I<1>

=item Adwm*B<selected.shadow>: I<#394870>

=item Adwm*B<selected.border>: I<#5369a3>

=item Adwm*B<selected.button>: I<#f0f0f0>

=item Adwm*B<selected.bg>:     I<#161616>

=item Adwm*B<selected.fg>:     I<#c0e0ff>

=item

=item Adwm*B<normal.font>:     I<Liberation Sans:size=9:medium>

=item Adwm*B<normal.drop>:     I<1>

=item Adwm*B<normal.shadow>:   I<#373737>

=item Adwm*B<normal.border>:   I<#373737>

=item Adwm*B<normal.button>:   I<#9c9c9c>

=item Adwm*B<normal.bg>:       I<#373737>

=item Adwm*B<normal.fg>:       I<#a9a9a9>

=item

=back

=back

=item B<button.E<lt>buttonE<gt>>[B<.toggled>][B<.disabled>].E<lt>stateE<gt>.pixmap> I<E<lt>pixmapE<gt>>

Specifies the pixmap to be used for the various buttons in various
states.

=over

=item B<E<lt>buttonE<gt>>

Specifies to which button the style elements apply and can be one of:

B<>    B<iconify>   minimize button;
    B<maximize>  maximize button;
    B<close>     close button;
    B<shade>     window shade button;
    B<stick>     window pin button;
    B<lhalf>     left-half maximus button;
    B<rhalf>     right-half maximus button;
    B<float>     float/tiled button; and,
    B<meu>       window menu button.

=item [B<.toggle>]

Use optionally for buttons that can be toggled (such as maximize).  It
indicates the toggled state (e.g. maximized) rather than the normal
state (e.g. unmaximized).

=item [B<.disabled>]

Used optionally for buttons that can be disabled (e.g. maximize) that
are disabled for some windows (e.g. windows that cannot be resized).

=item B<E<lt>stateE<gt>>

Specifies the state of the button and can be one of the following:

B<>    B<..>       normal state of the button;
    B<pressed>  while a mouse button is held down on the button;
    B<hovered>  while the point is hovering over the button;
    B<focused>  while the window is focussed; and,
    B<unfocus>  when the window is not focused.

=back

Example:

=over

=over

=item Adwm*B<button.shade.pixmap>: I<sfocus.xpm>

=item Adwm*B<button.shade.pressed.pixmap>: I<spress.xpm>

=item Adwm*B<button.shade.hovered.pixmap>: I<shover.xpm>

=item Adwm*B<button.shade.focused.pixmap>: I<sfocus.xpm>

=item Adwm*B<button.shade.unfocus.pixmap>: I<sunfoc.xpm>

=item Adwm*B<button.shade.disabled.hovered>: I<sunfoc.xpm>

=item Adwm*B<button.shade.disabled.focused>: I<sunfoc.xpm>

=item Adwm*B<button.shade.disabled.unfocus>: I<sunfoc.xpm>

=item

=item Adwm*B<button.shade.toggled.pixmap>: I<Ufocus.xpm>

=item Adwm*B<button.shade.toggled.pressed.pixmap>: I<Upress.xpm>

=item Adwm*B<button.shade.toggled.hovered.pixmap>: I<Uhover.xpm>

=item Adwm*B<button.shade.toggled.focused.pixmap>: I<Ufocus.xpm>

=item Adwm*B<button.shade.toggled.unfocus.pixmap>: I<Uunfoc.xpm>

=item Adwm*B<button.shade.toggled.disabled.hovered>: I<Uunfoc.xpm>

=item Adwm*B<button.shade.toggled.disabled.focused>: I<Uunfoc.xpm>

=item Adwm*B<button.shade.toggled.disabled.unfocus>: I<Uunfoc.xpm>

=back

=back

=back

=head1 DEFAULTS

The default style is provided in the default style file, typically,
F<$HOME/.adwm/stylerc>.

=head1 SEE ALSO

L<adwm(1)>, L<adwm-config(5)>, L<adwm-keys(5)>, L<adwm-styles(5)>.

=head1 BUGS

No outstanding bugs.

=head1 AUTHOR

Brian Bidulock <bidulock@openss7.org>

=cut

# vim: set nocin ft=pod tw=72 spell:
